---
  - name: Install common software packages
    become: true
    yum:
      state: present
      name: 
        - sysstat
        - iotop
        - screen

  - name: install the nginx rpm from a remote repo
    yum:
      state: present
      name: "{{ epel_url }}"
  
  - name: Install rlwrap software package
    become: true
    yum:
      state: present
      name: 
        - rlwrap

